version: 2.1

jobs:
  echo:
    parallelism: 4
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Greet
          command: echo "Please give me ${COLOR} builds..."
          environment:
            COLOR: "green"

workflows:
  main:
    jobs:
      - echo
